version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/monorepo-vm
    depends_on:
      - postgres
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        - DB_URL=postgresql://postgres:postgres@postgres:5432/monorepo-vm
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/monorepo-vm
    depends_on:
      - postgres
  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/monorepo-vm
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monorepo-vm
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
