version: '3.8'

services:
   postgres:
    image: postgres
    environment:
      -  POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=dilli03
      - POSTGRES_DB=monorepo-vm
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
   
   backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://postgres:dilli03@postgres:5432/monorepo-vm
    depends_on:
      - postgres
   ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:dilli03@postgres:5432/monorepo-vm
    depends_on:
      - postgres

   frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        - SKIP_BUILD_DB=true 
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres

   

volumes:
  postgres_data:
