FROM oven/bun:1

WORKDIR /app

COPY ./packages ./packages
COPY ./package.json  ./package.json
COPY ./bun.lock ./bun.lock
COPY  ./turbo.json ./turbo.json

COPY ./apps/http-server ./apps/http-server



RUN bun install

RUN bun run generate:db

EXPOSE 8081
CMD [ "bun","run","start:backend" ]