FROM oven/bun:1

WORKDIR /app

# Copy dependencies first
COPY ./package.json ./bun.lock ./turbo.json ./
COPY ./packages ./packages
RUN bun install

# Copy websocket code
COPY ./apps/web-socket ./apps/web-socket

# Generate DB client
RUN bun run generate:db

EXPOSE 8080
CMD ["bun", "run", "start:websocket"]
