FROM oven/bun:1

WORKDIR /app

# Copy only dependency files first for better caching
COPY ./package.json ./bun.lock ./turbo.json ./
COPY ./packages ./packages
RUN bun install

# Copy backend code
COPY ./apps/http-server ./apps/http-server

# Generate DB client
RUN bun run generate:db

EXPOSE 8081
CMD ["bun", "run", "start:backend"]
