FROM oven/bun:1

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

COPY ./package.json ./bun.lock ./turbo.json ./
COPY ./packages ./packages
COPY ./apps/web/package.json ./apps/web/package.json
RUN bun install

COPY ./apps/web ./apps/web

# Build flag: skip DB connection at build
ARG SKIP_BUILD_DB=false
RUN if [ "$SKIP_BUILD_DB" = "true" ]; then \
      echo "Skipping DB during build"; \
    else \
      bun run build; \
    fi

EXPOSE 3000
CMD ["bun","run","start:web"]
