FROM oven/bun:1

WORKDIR /app

COPY ./packages ./packages
COPY ./package.json  ./package.json
COPY ./bun.lock ./bun.lock
COPY  ./turbo.json ./turbo.json

COPY ./apps/web-socket ./apps/web-socket


RUN bun install

RUN bun run generate:db

EXPOSE 8080
CMD [ "bun","run","start:websocket" ]