name: Deploy the frontend of monorepo

on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
          push: true
          tags: dillax/user-app-frontend:${{ github.sha }}
        
      - name: Deploy to the Vm
        run: |
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
            chmod 600 ~/ssh_key
            ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.127.13.226 << EOF
              set -e
              IMAGE=dillax/user-app-backend:${GITHUB_SHA}
              sudo docker stop user_frontend_app || true
              sudo docker rm user_frontend_app || true
              
              sudo docker run --name user_frontend_app -d -p 3000:3000 \$IMAGE
            EOF